### ISSUE TITLE
Error: 805240832u | x has no effect

### ISSUE THREAD

**Issue by aferust** [BindBC/bindbc-sdl#20]
Windows 7 64 bit
LDC2 version 1.19.0 (DMD v2.089.1, LLVM 9.0.1)
```d
SDL_Window* window = SDL_CreateWindow(
        "SDL2/OpenGL Demo", 300, 100, SCREEN_WIDTH, SCREEN_HEIGHT, 
        SDL_WINDOW_OPENGL|SDL_WINDOW_RESIZABLE);
```

this works with v0.13.0 but not with v0.14.0:

bindbc-sdl-0.14.0\bindbc-sdl\source\bindbc\sdl\bind\sdlvideo.d(139,51): Error: 805240832u | x has no effect     
..dub\packages\bindbc-sdl-0.14.0\bindbc-sdl\source\bindbc\sdl\bind\sdlvideo.d(134,66):        called from here: SDL_WINDOWPOS_CENTERED_DISPLAY(0u)

**Comment by mdparker** [comment]
Yeah, I broke it. That's what I get for not testing my "harmless" changes. Fixed in 0.15.0. Thanks!
